export const LOGIN_SUCCESS = 'LOGIN SUCCESS';
export const LOGIN_FAILURE = 'LOGIN FAILURE';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAILURE = 'USER_LOADED_FAILURE';
export const LOGOUT = 'LOGOUT';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
export const RESET_PASSWORD_SEND_SUCCESS = 'RESET_PASSWORD_SEND_SUCCESS';
export const RESET_PASSWORD_SEND_FAILURE = 'RESET_PASSWORD_SEND_FAILURE';
export const RESET_PASSWORD_CONFIRM_SUCCESS = 'RESET_PASSWORD_CONFIRM_SUCCESS';
export const RESET_PASSWORD_CONFIRM_FAILURE = 'RESET_PASSWORD_CONFIRM_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAILURE = 'ACTIVATION_FAILURE';

export const GET_ITEM_SUCCESS = 'LIST_ITEM_SUCCESS';
export const GET_ITEM_FAIL = 'LIST_ITEM_FAIL';

export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAIL = 'REMOVE_FROM_CART_FAIL';
export const GET_CART = 'GET_CART';
export const GET_CART_FAIL = 'GET_CART_FAIL';
